#!/bin/sh

set -e

lb config noauto \
	--clean \
	--architectures amd64 \
  --apt apt \
  --apt-recommends true \
  --iso-application "Debian Junior Live" \
  --memtest none \
	--mode debian \
	--debian-installer live \
  --bootappend-live \
    "boot=live \
     autologin \
     lang=fr_FR.UTF-8 \
     locales=fr_FR.UTF-8 \
     keyboard-layouts=fr \
     keyboard-model=pc105 \
     timezone=Europe/Paris \
     utc=yes" \
"${@}"
